#!/bin/bash

if [ $# -lt 1 ];then
    echo "Need 1 parameters! <name> "
    exit
fi


R=$1

module load gcc
module load hisat2
module load samtools
module load bedtools

if [ -f /project/zanglab_project/jkx9nz/project/cut/HUMAN/RNA/${R}_r2.fastq.gz ]
then
hisat2 -p 8 --dta -x /nv/vol190/zanglab/sh8tv/Data/Mapping_index/Hisat2/hg38 -1 ${R}_r1.fastq.gz -2 ${R}_r2.fastq.gz -S ${R}_raw_stringtie.sam  2>&1 >>/dev/null |tee -a ${R}_hisat2PE.out

samtools view -bS ${R}_raw_stringtie.sam > ${R}_raw_stringtie.bam
samtools view -H ${R}_raw_stringtie.bam > ${R}_filtered_stringtie.sam
samtools view -f 0x2 ${R}_raw_stringtie.bam | awk 'NR % 2 == 1{mapq=$5;forward=$0} NR % 2 == 0{if($5>=30 && mapq>=30 && substr($3,1,3)=="chr" && $7=="=" ) print forward"\n"$0}' >> ${R}_filtered_stringtie.sam
samtools view -bS ${R}_filtered_stringtie.sam > ${R}_stringtie.bam
samtools sort -@ 8 -o ${R}_stringtie.bam ${R}_filtered_stringtie.sam

else
hisat2 -p 8 --dta -x /nv/vol190/zanglab/sh8tv/Data/Mapping_index/Hisat2/hg38 -U ${R}_r1.fastq.gz -S ${R}_raw_stringtie.sam  2>&1 >>/dev/null |tee -a ${R}_hisat2SE.out

samtools view -q 30 -bS ${R}_raw_stringtie.sam > ${R}_stringtie_filtered.bam 
samtools sort -@ 8 -o ${R}_stringtie.bam ${R}_stringtie_filtered.bam
fi

### stringtie rpkm
stringtie -e -B -p 8 -A ${R}_exp.txt -G /nv/vol190/zanglab/sh8tv/Data/refgenes/hg38/hg38_refgenes.gtf -o ${R}_stringtie.gtf ${R}_stringtie.bam
