#!/bin/bash

if [ $# -lt 1 ];then
    echo "Need 1 parameters! <SRR>  "
    exit
fi

module load gcc
module load bedtools
module load samtools
module load bowtie2

R=$1
###for pair-end
if [ -f /project/zanglab_project/jkx9nz/project/cut/FACTOR/HUMAN/new_acme3/${R}_2.fastq ]
then
bowtie2 -p 5 -X 2000 -x /nv/vol190/zanglab/sh8tv/Data/Mapping_index/bowtie2/hg38_clean -1 /project/zanglab_project/jkx9nz/project/cut/FACTOR/HUMAN/new_acme3/${R}_1.fastq -2 /project/zanglab_project/jkx9nz/project/cut/FACTOR/HUMAN/new_acme3/${R}_2.fastq -S ${R}.sam 2>&1 >>/dev/null | tee ${R}_bowtie2PE.out
samtools view -bS ${R}.sam > ${R}_raw.bam
samtools view -H ${R}_raw.bam > ${R}_filtered.sam
samtools view -f 0x2 ${R}_raw.bam | awk 'NR % 2 == 1{mapq=$5;forward=$0} NR % 2 == 0{if($5>=30 && mapq>=30 && substr($3,1,3)=="chr" && $7=="=" ) print forward"\n"$0}' >> ${R}_filtered.sam
samtools view -bS ${R}_filtered.sam > ${R}.bam
bamToBed -i ${R}.bam -bedpe | awk '{OFS="\t"; print $1,$2,$6,$7,$8,"."}' > ${R}_PE.bed
sort -k 1,1 -k 2,2g -k 3,3g ${R}_PE.bed |cut -f 1-3 |uniq > ${R}_PEuniq.bed
#rm ${R}_filtered.sam ${R}.sam
##bamToBed -i ${R}.bam -bedpe | awk '{OFS="\t"; print $1,$2,$6,$7,$8,"."}' | sort -k 1,1 -k 2,2g -k 3,3g|cut -f 1-3 |uniq > ${R}_PEuniq.bed
##python /nv/vol190/zanglab/sh8tv/Script/general/PEbed_To_rdSEbed.py -i ${R}_PE.bed -o ${R}_rdSE.bed
##python /nv/vol190/zanglab/sh8tv/Script/general/PEbed_To_rdSEbed.py -i ${R}_PEuniq.bed -o ${R}_rdSEuniq.bed

###for single-end
else
bowtie2 -p 5 -x /nv/vol190/zanglab/sh8tv/Data/Mapping_index/bowtie2/hg38_clean -U /project/zanglab_project/jkx9nz/project/cut/FACTOR/HUMAN/new_acme3/${R}_1.fastq -S ${R}.sam 2>&1 >>/dev/null | tee ${R}_bowtie2SE.out
samtools view -q 30 -bS ${R}.sam > ${R}.bam
bamToBed -i ${R}.bam > ${R}_SE.bed
#rm  ${R}.sam
fi
